### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by travbus** [biessek/fb-account-kit-example#1]
I got this example to work after i changed version="v1.1" and app id to my own.
Then I tried to make this work in my current app and i kept getting
Module not found: Error: Can't resolve 'vue-facebook-account-kit' in

I found that once i updated the dependencies in the fb-account-kit-example I started to get the same error I haven't traced out which one is causing the error yet.

**Comment by travbus** [comment]
Its something to do with webpack and I know idea how to do fix webpack issues unfortunately. Please help

**Comment by biessek** [comment]
Updated the example to match v0.1.2 of the vue-facebook-account-kit plugin
